// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Ingredient Types
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENT = 'GET_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_ALL_INGREDIENTS = 'DELETE_ALL_INGREDIENTS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
export const FILTER_INGREDIENTS = 'FILTER_INGREDIENTS';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const INGREDIENT_ERROR = 'INGREDIENT_ERROR';
export const SET_LOADING = 'SET_LOADING';

// Supplier Types
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const SET_CURRENT_SUPPLIER = 'SET_CURRENT_SUPPLIER';
export const CLEAR_CURRENT_SUPPLIER = 'CLEAR_CURRENT_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const FILTER_SUPPLIERS = 'FILTER_SUPPLIERS';
export const CLEAR_SUPPLIERS = 'CLEAR_SUPPLIERS';
export const SUPPLIER_ERROR = 'SUPPLIER_ERROR';

// Recipe Types
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';
export const CLEAR_CURRENT_RECIPE = 'CLEAR_CURRENT_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const FILTER_RECIPES = 'FILTER_RECIPES';
export const CLEAR_RECIPES = 'CLEAR_RECIPES';
export const RECIPE_ERROR = 'RECIPE_ERROR';

// Costing Types
export const CALCULATE_RECIPE_COST = 'CALCULATE_RECIPE_COST';
export const GET_COST_REPORTS = 'GET_COST_REPORTS';
export const SAVE_COST_CALCULATION = 'SAVE_COST_CALCULATION';
export const DELETE_COST_CALCULATION = 'DELETE_COST_CALCULATION';
export const SET_CURRENT_CALCULATION = 'SET_CURRENT_CALCULATION';
export const CLEAR_CURRENT_CALCULATION = 'CLEAR_CURRENT_CALCULATION';
export const COSTING_ERROR = 'COSTING_ERROR';
export const SET_COSTING_LOADING = 'SET_COSTING_LOADING';

// Import Types
export const IMPORT_SUCCESS = 'IMPORT_SUCCESS';
export const IMPORT_FAIL = 'IMPORT_FAIL';
export const CLEAR_IMPORT = 'CLEAR_IMPORT';

// Recipe Source Types
export const GET_RECIPE_SOURCES = 'GET_RECIPE_SOURCES';
export const ADD_RECIPE_SOURCE = 'ADD_RECIPE_SOURCE';
export const DELETE_RECIPE_SOURCE = 'DELETE_RECIPE_SOURCE';
export const SET_CURRENT_RECIPE_SOURCE = 'SET_CURRENT_RECIPE_SOURCE';
export const CLEAR_CURRENT_RECIPE_SOURCE = 'CLEAR_CURRENT_RECIPE_SOURCE';
export const UPDATE_RECIPE_SOURCE = 'UPDATE_RECIPE_SOURCE';
export const FILTER_RECIPE_SOURCES = 'FILTER_RECIPE_SOURCES';
export const CLEAR_RECIPE_SOURCE_FILTER = 'CLEAR_RECIPE_SOURCE_FILTER';
export const RECIPE_SOURCE_ERROR = 'RECIPE_SOURCE_ERROR';
export const CLEAR_RECIPE_SOURCES = 'CLEAR_RECIPE_SOURCES';

// Settings Types
export const GET_SETTINGS = 'GET_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';
export const SET_SETTINGS_LOADING = 'SET_SETTINGS_LOADING';

// Marketplace Types
export const GET_MARKETPLACE_RECIPES = 'GET_MARKETPLACE_RECIPES';
export const GET_MARKETPLACE_RECIPE = 'GET_MARKETPLACE_RECIPE';
export const GET_CATALOGS = 'GET_CATALOGS';
export const GET_CATALOG = 'GET_CATALOG';
export const IMPORT_RECIPE = 'IMPORT_RECIPE';
export const MARKETPLACE_ERROR = 'MARKETPLACE_ERROR';
export const SET_MARKETPLACE_LOADING = 'SET_MARKETPLACE_LOADING';
export const CLEAR_MARKETPLACE_ERROR = 'CLEAR_MARKETPLACE_ERROR';
export const FILTER_MARKETPLACE_RECIPES = 'FILTER_MARKETPLACE_RECIPES';
export const CLEAR_MARKETPLACE_FILTER = 'CLEAR_MARKETPLACE_FILTER';

// Settings
export const SET_CURRENCY_SYMBOL = 'SET_CURRENCY_SYMBOL';
export const SET_THOUSAND_SEPARATOR = 'SET_THOUSAND_SEPARATOR'; 